server:
  port: 8123
  servlet:
    context-path: /api
  address: 0.0.0.0
spring:
  application:
    name: ai-3d-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ai_3d?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    # 开发环境中日志输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值

knife4j:
  enable: true
  openapi:
    title: 接口文档
    version: 1.0
    group:
      default:
        group-name: 默认分组
        api-rule: package
        api-rule-resources:
          - com.elwg.ai3dbackend.controller

deepseek:
  api:
    key: ${DEEPSEEK_API_KEY}
    url: https://api.deepseek.com/v1/chat/completions
    model: deepseek-chat
    connect-timeout: 30
    read-timeout: 30
    write-timeout: 30
    # 温度参数，控制生成文本的随机性
    temperature: 0.7
    # 最大令牌数
    max-tokens: 2048

# 文件上传配置已移至spring配置下

# 存储服务配置
storage:
  # 使用腾讯云COS存储
  type: cos

# 3D重建结果存储配置（使用COS存储）
reconstruction:
  # HTTP重建服务配置
  http:
    server:
      # Python服务器URL
      url: http://10.0.0.2:8001/generate3d
      # 健康检查URL
      health.url: http://10.0.0.2:8001/health
    connection:
      # 连接超时时间（秒）
      timeout: 30
      # 读取超时时间（秒）
      read.timeout: 300
      # 写入超时时间（秒）
      write.timeout: 30
  # 回调配置
  callback:
    # 回调主机名（可选，如果不设置则自动检测）
    # 设置为服务器的公网IP或域名，确保Python服务可以访问
    # host: your-server-ip-or-domain
    # 默认IP地址（当自动检测失败时使用）
    default-ip: 10.0.0.123

cos:
  client:
    host: https://3d-lab-1258032620.cos.ap-shanghai.myqcloud.com
    secretId: ${TC_SECRETID}
    secretKey: ${TC_SECRETKEY}
    region: ap-shanghai
    bucket: 3d-lab-1258032620